### your site title here

title: A blog about NLProc

permalink: /:title

url: http://taniaka.github.io
baseurl:
sass: 
    style: compressed


# Tracker
analytics: UA-83979019-1


exclude:
- README.md

include: 
- _pages
